# Generated by Django 4.2 on 2025-01-31 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, '1(Lowest)'), (2, '2(Low)'), (3, '3(middle)'), (4, '4(High)'), (5, '5(Highest)')], default=3),
        ),
    ]
